CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_SENSOR=y
CONFIG_BOOT_DELAY=500
CONFIG_I2C=y
CONFIG_DISPLAY=y
CONFIG_COUNTER=y
CONFIG_TIMING_FUNCTIONS=y
CONFIG_SENSOR_ASYNC_API=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_STACK_SENTINEL=y
CONFIG_HW_STACK_PROTECTION=y
CONFIG_INPUT=y
CONFIG_PICOLIBC=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
# CONFIG_INPUT_EVENT_DUMP=y
CONFIG_INPUT_MODE_SYNCHRONOUS=y
CONFIG_TICKLESS_KERNEL=y
CONFIG_SYS_CLOCK_TICKS_PER_SEC=100000